services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql

    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - .docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
  order-service:
      image: mysql  # Replace with your actual image name
      depends_on:
        - mysql
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3307/order_service  # Update URL accordingly if using localhost
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: mysql